apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jexmpl.fullname" . }}
  labels:
    app: {{ template "jexmpl.name" . }}
    chart: {{ template "jexmpl.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  author.txt: |
    avoidik@gmail.com
