apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jexmpl.fullname" . }}-db
  labels:
    app: {{ template "jexmpl.name" . }}
    chart: {{ template "jexmpl.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{ .Values.mysql.mysqlUser }}: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
